# Generated by Django 3.2.7 on 2021-11-21 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administradores', '0001_initial'),
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'Carrito',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('historial', models.CharField(blank=True, default='', max_length=500)),
                ('carrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientes.carrito')),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('NW', 'Nuevo'), ('OK', 'Aceptado'), ('DN', 'Rechazado'), ('OG', 'En Proceso'), ('DL', 'Entregado')], default='NW', max_length=2)),
                ('autor', models.CharField(max_length=80, null=True)),
                ('ISBN', models.CharField(max_length=13)),
                ('titulo', models.CharField(max_length=100)),
                ('administrador_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administradores.administrador')),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'db_table': 'Reserva',
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=280, null=True)),
                ('puntuacion', models.FloatField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('cliente_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('libro_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libros.libro')),
            ],
            options={
                'db_table': 'Resena',
            },
        ),
        migrations.CreateModel(
            name='LibroCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('carrito_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.carrito')),
                ('libro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro')),
            ],
            options={
                'db_table': 'LibroCarrito',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='reservas',
            field=models.ManyToManyField(through='clientes.Reserva', to='administradores.Administrador'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='reseñas',
            field=models.ManyToManyField(through='clientes.Resena', to='libros.Libro'),
        ),
    ]
