# Generated by Django 3.2.7 on 2021-10-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='id',
        ),
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='libro',
            name='edicion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='libro',
            name='idioma',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='libro',
            name='noPaginas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='nuevo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='libros/pictures'),
        ),
        migrations.AddField(
            model_name='libro',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='presentacion',
            field=models.CharField(choices=[('TD', 'Tapa dura'), ('TB', 'Tapa blanda'), ('NN', 'None')], default='NN', max_length=2),
        ),
        migrations.AddField(
            model_name='libro',
            name='preventa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='libro',
            name='puntuacion',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='libro',
            name='ISBN',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
