# Generated by Django 3.2.7 on 2021-10-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20211002_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='puntuacion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
