# Generated by Django 3.2.7 on 2021-10-15 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('libros', '0005_libro_url_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='carrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.carrito'),
        ),
    ]
