# Generated by Django 3.2.7 on 2021-10-15 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_libro_carrito'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='libro',
            table='Libro',
        ),
    ]
