# Generated by Django 3.2.7 on 2021-10-15 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0007_alter_libro_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='carrito',
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=280, null=True)),
                ('puntuacion', models.FloatField(blank=True, null=True)),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libros.libro')),
            ],
            options={
                'db_table': 'Resena',
            },
        ),
    ]
