# Generated by Django 3.2.7 on 2021-10-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0008_auto_20211014_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('fechaNacimiento', models.DateField()),
                ('libros', models.ManyToManyField(to='libros.Libro')),
            ],
            options={
                'db_table': 'Autor',
            },
        ),
    ]
