# Generated by Django 3.2.7 on 2021-10-16 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0009_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
