# Generated by Django 3.2.7 on 2021-10-16 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0010_libro_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
