# Generated by Django 3.2.7 on 2021-10-25 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'Carrito',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ni', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('carrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='compras.carrito')),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=280, null=True)),
                ('puntuacion', models.FloatField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('cliente_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.cliente')),
                ('libro_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libros.libro')),
            ],
            options={
                'db_table': 'Resena',
            },
        ),
        migrations.CreateModel(
            name='LibroCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('carrito_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.carrito')),
                ('libro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro')),
            ],
            options={
                'db_table': 'LibroCarrito',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(max_length=25)),
                ('metodo_envio', models.CharField(max_length=25)),
                ('costo_total', models.BigIntegerField()),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.cliente')),
            ],
            options={
                'db_table': 'Compra',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='reseñas',
            field=models.ManyToManyField(through='compras.Resena', to='libros.Libro'),
        ),
    ]
