# Generated by Django 3.2.7 on 2021-10-15 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carrito',
            table='Carrito',
        ),
    ]
