# Generated by Django 3.2.7 on 2021-10-15 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0008_auto_20211014_2218'),
        ('compras', '0002_alter_carrito_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('carrito_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.carrito')),
                ('libro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro')),
            ],
            options={
                'db_table': 'LibroCarrito',
            },
        ),
    ]
