# Generated by Django 3.2.7 on 2021-10-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_carrito_libro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='libro',
            new_name='libros',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
