# Generated by Django 3.2.7 on 2021-11-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('fechaFin', models.DateTimeField()),
                ('portada', models.ImageField(upload_to='libros/pictures')),
            ],
            options={
                'db_table': 'Evento',
            },
        ),
    ]
