<<<<<<< HEAD
# Generated by Django 3.2.7 on 2021-11-18 00:31

from django.db import migrations, models
=======
# Generated by Django 3.2.7 on 2021-11-21 16:23

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 72118169c08760ec4598878a2a7aef1ea10fccf9


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('administradores', '0001_initial'),
>>>>>>> 72118169c08760ec4598878a2a7aef1ea10fccf9
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('fechaFin', models.DateTimeField()),
                ('portada', models.ImageField(upload_to='libros/pictures')),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='novedades/images')),
                ('administrador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administradores.administrador')),
>>>>>>> 72118169c08760ec4598878a2a7aef1ea10fccf9
            ],
            options={
                'db_table': 'Evento',
            },
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='novedades/images')),
                ('administrador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administradores.administrador')),
            ],
            options={
                'db_table': 'Descuento',
            },
        ),
>>>>>>> 72118169c08760ec4598878a2a7aef1ea10fccf9
    ]
